[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  PRISMA_DISABLE_PREPARED_STATEMENTS = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[[plugins]]
  package = "@netlify/plugin-nextjs" 